import type { Metadata } from "next";
import "./globals.css";
import { TopBar } from "../components/common/top-bar/top-bar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: "url('/pictures/tool-4.jpg')",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <TopBar />
        {children}
      </body>
    </html>
  );
}
